apps:
  - name: spresstest
    script: /app/dist/main.js
    instances: 4
    autorestart: true
    watch: false
    max_memory_restart: 1G
    env:
      NODE_ENV: production
    output: /output.log
    error_file: /error.log
    out_file: /out.log
    log_date_format: "YYYY-MM-DD HH:mm:ss"  
